language: node_js
node_js:
    - lts/*
install:
    - yarn install # npm ci
cache:
    bundle: true
    directories:
        - node_modules
script:
    - npm test
    - npm run build:pages
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: pages/
    on:
        branch: master
